name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - name: Generate protobufs
        run: |
          buf dep update
          buf generate
      - name: Build
        run: go build ./...
      - name: Unit tests
        run: go test ./...
